overrides:
  '@orval/core@<7.19.0': '>=7.19.0'
  '@orval/core@>=7.19.0 <7.21.0': '>=7.21.0'
  '@orval/core@>=8.0.0-rc.0 <8.0.2': '>=8.0.2'
  '@orval/mcp@<7.18.0': '>=7.18.0'
  '@orval/mock@<7.20.0': '>=7.20.0'
  ajv@>=7.0.0-alpha.0 <8.18.0: '>=8.18.0'
  axios@<=1.13.4: '>=1.13.5'
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
  minimatch@>=5.0.0 <5.1.7: '>=5.1.7'
  minimatch@>=9.0.0 <9.0.6: '>=9.0.6'
