export const USDC_MAINNET_MINT_ADDRESS =
  'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v'

export const USDC_DEVNET_MINT_ADDRESS =
  '4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU'

export const DEFAULT_COMPUTE_UNIT_LIMIT = 200_000

export const DEFAULT_COMPUTE_UNIT_PRICE = 1_000_000n
