/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://openfort.xyz/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { TransactionIntentResponse } from './transactionIntentResponse';

export class AccountResponse {
    'id': string;
    'createdAt': Date;
    'address': string;
    'deployed': boolean;
    'object': string;
    'chainId': number;
    'transactionIntents': Array<TransactionIntentResponse>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date"
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "string"
        },
        {
            "name": "deployed",
            "baseName": "deployed",
            "type": "boolean"
        },
        {
            "name": "object",
            "baseName": "object",
            "type": "string"
        },
        {
            "name": "chainId",
            "baseName": "chain_id",
            "type": "number"
        },
        {
            "name": "transactionIntents",
            "baseName": "transaction_intents",
            "type": "Array<TransactionIntentResponse>"
        }    ];

    static getAttributeTypeMap() {
        return AccountResponse.attributeTypeMap;
    }
}

