/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://openfort.xyz/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AllowFunctionResponse } from './allowFunctionResponse';
import { Strategy } from './strategy';

export class PolicyResponse {
    'id': string;
    'createdAt': Date;
    'name': string | null;
    'chainId': number;
    'strategy': Strategy;
    'transactionIntents': Array<any>;
    'allowFunctions': Array<AllowFunctionResponse>;
    'object': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "chainId",
            "baseName": "chain_id",
            "type": "number"
        },
        {
            "name": "strategy",
            "baseName": "strategy",
            "type": "Strategy"
        },
        {
            "name": "transactionIntents",
            "baseName": "transaction_intents",
            "type": "Array<any>"
        },
        {
            "name": "allowFunctions",
            "baseName": "allow_functions",
            "type": "Array<AllowFunctionResponse>"
        },
        {
            "name": "object",
            "baseName": "object",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return PolicyResponse.attributeTypeMap;
    }
}

