/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://openfort.xyz/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from "./models";

export class SessionResponse {
  "id": string;
  "object": string;
  "createdAt": Date;
  "validAfter"?: string;
  "validUntil"?: string;
  "whitelist"?: Array<string>;
  "limit"?: number;
  "nextAction": object | null;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: "id",
      baseName: "id",
      type: "string",
    },
    {
      name: "object",
      baseName: "object",
      type: "string",
    },
    {
      name: "createdAt",
      baseName: "created_at",
      type: "Date",
    },
    {
      name: "validAfter",
      baseName: "valid_after",
      type: "string",
    },
    {
      name: "validUntil",
      baseName: "valid_until",
      type: "string",
    },
    {
      name: "whitelist",
      baseName: "whitelist",
      type: "Array<string>",
    },
    {
      name: "limit",
      baseName: "limit",
      type: "number",
    },
    {
      name: "nextAction",
      baseName: "next_action",
      type: "object",
    },
  ];

  static getAttributeTypeMap() {
    return SessionResponse.attributeTypeMap;
  }
}
