/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://openfort.xyz/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from "./models";

export class UserOpResult {
  "transactionHash": string;
  "success": boolean;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: "transactionHash",
      baseName: "transactionHash",
      type: "string",
    },
    {
      name: "success",
      baseName: "success",
      type: "boolean",
    },
  ];

  static getAttributeTypeMap() {
    return UserOpResult.attributeTypeMap;
  }
}
