/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://openfort.xyz/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import localVarRequest from "request";
import http from "http";

/* tslint:disable:no-unused-locals */
import { PolicyRuleResponse } from "../model/policyRuleResponse";
import { PolicyRulesResponse } from "../model/policyRulesResponse";
import { PolicySchema } from "../model/policySchema";

import {
  ObjectSerializer,
  Authentication,
  VoidAuth,
  Interceptor,
} from "../model/models";
import {
  HttpBasicAuth,
  HttpBearerAuth,
  ApiKeyAuth,
  OAuth,
} from "../model/models";

import { HttpError, RequestFile } from "./apis";

let defaultBasePath = "https://api.openfort.xyz";

// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================

export enum DefaultApiApiKeys {}

export class DefaultApi {
  protected _basePath = defaultBasePath;
  protected _defaultHeaders: any = {};
  protected _useQuerystring: boolean = false;

  protected authentications = {
    default: <Authentication>new VoidAuth(),
    pk: new HttpBearerAuth(),
  };

  protected interceptors: Interceptor[] = [];

  constructor(basePath?: string);
  constructor(
    basePathOrUsername: string,
    password?: string,
    basePath?: string
  ) {
    if (password) {
      if (basePath) {
        this.basePath = basePath;
      }
    } else {
      if (basePathOrUsername) {
        this.basePath = basePathOrUsername;
      }
    }
  }

  set useQuerystring(value: boolean) {
    this._useQuerystring = value;
  }

  set basePath(basePath: string) {
    this._basePath = basePath;
  }

  set defaultHeaders(defaultHeaders: any) {
    this._defaultHeaders = defaultHeaders;
  }

  get defaultHeaders() {
    return this._defaultHeaders;
  }

  get basePath() {
    return this._basePath;
  }

  public setDefaultAuthentication(auth: Authentication) {
    this.authentications.default = auth;
  }

  public setApiKey(key: DefaultApiApiKeys, value: string) {
    (this.authentications as any)[DefaultApiApiKeys[key]].apiKey = value;
  }

  set accessToken(accessToken: string | (() => string)) {
    this.authentications.pk.accessToken = accessToken;
  }

  public addInterceptor(interceptor: Interceptor) {
    this.interceptors.push(interceptor);
  }

  /**
   * Creates an allow function object.
   * @param type
   * @param functionName
   * @param policy
   * @param contract
   * @param project
   */
  public async createPolicyRules(
    type: PolicySchema,
    functionName: string,
    policy: string,
    contract: string,
    project?: string,
    options: { headers: { [name: string]: string } } = { headers: {} }
  ): Promise<{ response: http.IncomingMessage; body: PolicyRuleResponse }> {
    const localVarPath = this.basePath + "/v1/policy_rules";
    let localVarQueryParameters: any = {};
    let localVarHeaderParams: any = (<any>Object).assign(
      {},
      this._defaultHeaders
    );
    const produces = ["application/json"];
    // give precedence to 'application/json'
    if (produces.indexOf("application/json") >= 0) {
      localVarHeaderParams.Accept = "application/json";
    } else {
      localVarHeaderParams.Accept = produces.join(",");
    }
    let localVarFormParams: any = {};

    // verify required parameter 'type' is not null or undefined
    if (type === null || type === undefined) {
      throw new Error(
        "Required parameter type was null or undefined when calling createPolicyRules."
      );
    }

    // verify required parameter 'functionName' is not null or undefined
    if (functionName === null || functionName === undefined) {
      throw new Error(
        "Required parameter functionName was null or undefined when calling createPolicyRules."
      );
    }

    // verify required parameter 'policy' is not null or undefined
    if (policy === null || policy === undefined) {
      throw new Error(
        "Required parameter policy was null or undefined when calling createPolicyRules."
      );
    }

    // verify required parameter 'contract' is not null or undefined
    if (contract === null || contract === undefined) {
      throw new Error(
        "Required parameter contract was null or undefined when calling createPolicyRules."
      );
    }

    (<any>Object).assign(localVarHeaderParams, options.headers);

    let localVarUseFormData = false;

    if (type !== undefined) {
      localVarFormParams["type"] = ObjectSerializer.serialize(
        type,
        "PolicySchema"
      );
    }

    if (functionName !== undefined) {
      localVarFormParams["function_name"] = ObjectSerializer.serialize(
        functionName,
        "string"
      );
    }

    if (policy !== undefined) {
      localVarFormParams["policy"] = ObjectSerializer.serialize(
        policy,
        "string"
      );
    }

    if (project !== undefined) {
      localVarFormParams["project"] = ObjectSerializer.serialize(
        project,
        "string"
      );
    }

    if (contract !== undefined) {
      localVarFormParams["contract"] = ObjectSerializer.serialize(
        contract,
        "string"
      );
    }

    let localVarRequestOptions: localVarRequest.Options = {
      method: "POST",
      qs: localVarQueryParameters,
      headers: localVarHeaderParams,
      uri: localVarPath,
      useQuerystring: this._useQuerystring,
      json: true,
    };

    let authenticationPromise = Promise.resolve();
    if (this.authentications.pk.accessToken) {
      authenticationPromise = authenticationPromise.then(() =>
        this.authentications.pk.applyToRequest(localVarRequestOptions)
      );
    }
    authenticationPromise = authenticationPromise.then(() =>
      this.authentications.default.applyToRequest(localVarRequestOptions)
    );

    let interceptorPromise = authenticationPromise;
    for (const interceptor of this.interceptors) {
      interceptorPromise = interceptorPromise.then(() =>
        interceptor(localVarRequestOptions)
      );
    }

    return interceptorPromise.then(() => {
      if (Object.keys(localVarFormParams).length) {
        if (localVarUseFormData) {
          (<any>localVarRequestOptions).formData = localVarFormParams;
        } else {
          localVarRequestOptions.form = localVarFormParams;
        }
      }
      return new Promise<{
        response: http.IncomingMessage;
        body: PolicyRuleResponse;
      }>((resolve, reject) => {
        localVarRequest(localVarRequestOptions, (error, response, body) => {
          if (error) {
            reject(error);
          } else {
            if (
              response.statusCode &&
              response.statusCode >= 200 &&
              response.statusCode <= 299
            ) {
              body = ObjectSerializer.deserialize(body, "PolicyRuleResponse");
              resolve({ response: response, body: body });
            } else {
              reject(new HttpError(response, body, response.statusCode));
            }
          }
        });
      });
    });
  }
  /**
   * Returns a list of your allow functions for the given policy. The allow functions are returned sorted by creation date, with the most recently created allow functions appearing first.
   * @param project Specifies the unique project ID.
   * @param policy Specifies the unique policy ID.
   */
  public async getPolicyRules(
    project?: string,
    policy?: string,
    options: { headers: { [name: string]: string } } = { headers: {} }
  ): Promise<{ response: http.IncomingMessage; body: PolicyRulesResponse }> {
    const localVarPath = this.basePath + "/v1/policy_rules";
    let localVarQueryParameters: any = {};
    let localVarHeaderParams: any = (<any>Object).assign(
      {},
      this._defaultHeaders
    );
    const produces = ["application/json"];
    // give precedence to 'application/json'
    if (produces.indexOf("application/json") >= 0) {
      localVarHeaderParams.Accept = "application/json";
    } else {
      localVarHeaderParams.Accept = produces.join(",");
    }
    let localVarFormParams: any = {};

    if (project !== undefined) {
      localVarQueryParameters["project"] = ObjectSerializer.serialize(
        project,
        "string"
      );
    }

    if (policy !== undefined) {
      localVarQueryParameters["policy"] = ObjectSerializer.serialize(
        policy,
        "string"
      );
    }

    (<any>Object).assign(localVarHeaderParams, options.headers);

    let localVarUseFormData = false;

    let localVarRequestOptions: localVarRequest.Options = {
      method: "GET",
      qs: localVarQueryParameters,
      headers: localVarHeaderParams,
      uri: localVarPath,
      useQuerystring: this._useQuerystring,
      json: true,
    };

    let authenticationPromise = Promise.resolve();
    if (this.authentications.pk.accessToken) {
      authenticationPromise = authenticationPromise.then(() =>
        this.authentications.pk.applyToRequest(localVarRequestOptions)
      );
    }
    authenticationPromise = authenticationPromise.then(() =>
      this.authentications.default.applyToRequest(localVarRequestOptions)
    );

    let interceptorPromise = authenticationPromise;
    for (const interceptor of this.interceptors) {
      interceptorPromise = interceptorPromise.then(() =>
        interceptor(localVarRequestOptions)
      );
    }

    return interceptorPromise.then(() => {
      if (Object.keys(localVarFormParams).length) {
        if (localVarUseFormData) {
          (<any>localVarRequestOptions).formData = localVarFormParams;
        } else {
          localVarRequestOptions.form = localVarFormParams;
        }
      }
      return new Promise<{
        response: http.IncomingMessage;
        body: PolicyRulesResponse;
      }>((resolve, reject) => {
        localVarRequest(localVarRequestOptions, (error, response, body) => {
          if (error) {
            reject(error);
          } else {
            if (
              response.statusCode &&
              response.statusCode >= 200 &&
              response.statusCode <= 299
            ) {
              body = ObjectSerializer.deserialize(body, "PolicyRulesResponse");
              resolve({ response: response, body: body });
            } else {
              reject(new HttpError(response, body, response.statusCode));
            }
          }
        });
      });
    });
  }
  /**
   * Updates your allow functions object.
   * @param id Specifies the unique allow function ID.
   * @param type
   * @param functionName
   * @param policy
   * @param contract
   * @param project
   */
  public async updatePolicyRules(
    id: string,
    type: PolicySchema,
    functionName: string,
    policy: string,
    contract: string,
    project?: string,
    options: { headers: { [name: string]: string } } = { headers: {} }
  ): Promise<{ response: http.IncomingMessage; body: PolicyRuleResponse }> {
    const localVarPath =
      this.basePath +
      "/v1/policy_rules/{id}".replace(
        "{" + "id" + "}",
        encodeURIComponent(String(id))
      );
    let localVarQueryParameters: any = {};
    let localVarHeaderParams: any = (<any>Object).assign(
      {},
      this._defaultHeaders
    );
    const produces = ["application/json"];
    // give precedence to 'application/json'
    if (produces.indexOf("application/json") >= 0) {
      localVarHeaderParams.Accept = "application/json";
    } else {
      localVarHeaderParams.Accept = produces.join(",");
    }
    let localVarFormParams: any = {};

    // verify required parameter 'id' is not null or undefined
    if (id === null || id === undefined) {
      throw new Error(
        "Required parameter id was null or undefined when calling updatePolicyRules."
      );
    }

    // verify required parameter 'type' is not null or undefined
    if (type === null || type === undefined) {
      throw new Error(
        "Required parameter type was null or undefined when calling updatePolicyRules."
      );
    }

    // verify required parameter 'functionName' is not null or undefined
    if (functionName === null || functionName === undefined) {
      throw new Error(
        "Required parameter functionName was null or undefined when calling updatePolicyRules."
      );
    }

    // verify required parameter 'policy' is not null or undefined
    if (policy === null || policy === undefined) {
      throw new Error(
        "Required parameter policy was null or undefined when calling updatePolicyRules."
      );
    }

    // verify required parameter 'contract' is not null or undefined
    if (contract === null || contract === undefined) {
      throw new Error(
        "Required parameter contract was null or undefined when calling updatePolicyRules."
      );
    }

    (<any>Object).assign(localVarHeaderParams, options.headers);

    let localVarUseFormData = false;

    if (type !== undefined) {
      localVarFormParams["type"] = ObjectSerializer.serialize(
        type,
        "PolicySchema"
      );
    }

    if (functionName !== undefined) {
      localVarFormParams["function_name"] = ObjectSerializer.serialize(
        functionName,
        "string"
      );
    }

    if (policy !== undefined) {
      localVarFormParams["policy"] = ObjectSerializer.serialize(
        policy,
        "string"
      );
    }

    if (project !== undefined) {
      localVarFormParams["project"] = ObjectSerializer.serialize(
        project,
        "string"
      );
    }

    if (contract !== undefined) {
      localVarFormParams["contract"] = ObjectSerializer.serialize(
        contract,
        "string"
      );
    }

    let localVarRequestOptions: localVarRequest.Options = {
      method: "POST",
      qs: localVarQueryParameters,
      headers: localVarHeaderParams,
      uri: localVarPath,
      useQuerystring: this._useQuerystring,
      json: true,
    };

    let authenticationPromise = Promise.resolve();
    if (this.authentications.pk.accessToken) {
      authenticationPromise = authenticationPromise.then(() =>
        this.authentications.pk.applyToRequest(localVarRequestOptions)
      );
    }
    authenticationPromise = authenticationPromise.then(() =>
      this.authentications.default.applyToRequest(localVarRequestOptions)
    );

    let interceptorPromise = authenticationPromise;
    for (const interceptor of this.interceptors) {
      interceptorPromise = interceptorPromise.then(() =>
        interceptor(localVarRequestOptions)
      );
    }

    return interceptorPromise.then(() => {
      if (Object.keys(localVarFormParams).length) {
        if (localVarUseFormData) {
          (<any>localVarRequestOptions).formData = localVarFormParams;
        } else {
          localVarRequestOptions.form = localVarFormParams;
        }
      }
      return new Promise<{
        response: http.IncomingMessage;
        body: PolicyRuleResponse;
      }>((resolve, reject) => {
        localVarRequest(localVarRequestOptions, (error, response, body) => {
          if (error) {
            reject(error);
          } else {
            if (
              response.statusCode &&
              response.statusCode >= 200 &&
              response.statusCode <= 299
            ) {
              body = ObjectSerializer.deserialize(body, "PolicyRuleResponse");
              resolve({ response: response, body: body });
            } else {
              reject(new HttpError(response, body, response.statusCode));
            }
          }
        });
      });
    });
  }
}
