/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://openfort.xyz/docs
 *
 * OpenAPI spec version: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Fragment } from '../models/Fragment';
import { JsonFragment } from '../models/JsonFragment';
import { HttpFile } from '../http/http';

export class ContractResponseAbiAnyOfInner {
    'type': string;
    'name': string;
    'inputs': any;
    'isFragment': boolean;
    'anonymous'?: boolean;
    'payable'?: boolean;
    'constant'?: boolean;
    'stateMutability'?: string;
    'outputs'?: any;
    'gas'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "inputs",
            "baseName": "inputs",
            "type": "any",
            "format": ""
        },
        {
            "name": "isFragment",
            "baseName": "_isFragment",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "anonymous",
            "baseName": "anonymous",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "payable",
            "baseName": "payable",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "constant",
            "baseName": "constant",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "stateMutability",
            "baseName": "stateMutability",
            "type": "string",
            "format": ""
        },
        {
            "name": "outputs",
            "baseName": "outputs",
            "type": "any",
            "format": ""
        },
        {
            "name": "gas",
            "baseName": "gas",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ContractResponseAbiAnyOfInner.attributeTypeMap;
    }

    public constructor() {
    }
}

