/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://openfort.xyz/docs
 *
 * OpenAPI spec version: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ParamType } from '../models/ParamType';
import { HttpFile } from '../http/http';

export class Fragment {
    'type': string;
    'name': string;
    'inputs': Array<ParamType>;
    'isFragment': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "inputs",
            "baseName": "inputs",
            "type": "Array<ParamType>",
            "format": ""
        },
        {
            "name": "isFragment",
            "baseName": "_isFragment",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Fragment.attributeTypeMap;
    }

    public constructor() {
    }
}

