/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://openfort.xyz/docs
 *
 * OpenAPI spec version: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ParamType {
    'name': string;
    'type': string;
    'baseType': string;
    'indexed': boolean;
    'components': Array<ParamType>;
    'arrayLength': number;
    'arrayChildren': ParamType;
    'isParamType': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "baseType",
            "baseName": "baseType",
            "type": "string",
            "format": ""
        },
        {
            "name": "indexed",
            "baseName": "indexed",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "components",
            "baseName": "components",
            "type": "Array<ParamType>",
            "format": ""
        },
        {
            "name": "arrayLength",
            "baseName": "arrayLength",
            "type": "number",
            "format": "double"
        },
        {
            "name": "arrayChildren",
            "baseName": "arrayChildren",
            "type": "ParamType",
            "format": ""
        },
        {
            "name": "isParamType",
            "baseName": "_isParamType",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ParamType.attributeTypeMap;
    }

    public constructor() {
    }
}

