/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://openfort.xyz/docs
 *
 * OpenAPI spec version: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Interaction } from '../models/Interaction';
import { ResponseResponse } from '../models/ResponseResponse';
import { UserOpResult } from '../models/UserOpResult';
import { HttpFile } from '../http/http';

export class TransactionIntentResponse {
    'id': string;
    'createdAt': Date;
    'updatedAt': Date;
    'chainId': number;
    'userOperationHash': string | null;
    'userOperation'?: UserOpResult;
    'policy': string | null;
    'player': string;
    'account'?: string;
    'transactions': Array<Interaction>;
    'response': ResponseResponse | null;
    'object': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "chainId",
            "baseName": "chain_id",
            "type": "number",
            "format": "double"
        },
        {
            "name": "userOperationHash",
            "baseName": "user_operation_hash",
            "type": "string",
            "format": ""
        },
        {
            "name": "userOperation",
            "baseName": "user_operation",
            "type": "UserOpResult",
            "format": ""
        },
        {
            "name": "policy",
            "baseName": "policy",
            "type": "string",
            "format": ""
        },
        {
            "name": "player",
            "baseName": "player",
            "type": "string",
            "format": ""
        },
        {
            "name": "account",
            "baseName": "account",
            "type": "string",
            "format": ""
        },
        {
            "name": "transactions",
            "baseName": "transactions",
            "type": "Array<Interaction>",
            "format": ""
        },
        {
            "name": "response",
            "baseName": "response",
            "type": "ResponseResponse",
            "format": ""
        },
        {
            "name": "object",
            "baseName": "object",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TransactionIntentResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

