/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://openfort.xyz/docs
 *
 * OpenAPI spec version: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TransactionIntentResponse } from '../models/TransactionIntentResponse';
import { HttpFile } from '../http/http';

export class AccountResponse {
    'id': string;
    'createdAt': Date;
    'address': string;
    'deployed': boolean;
    'object': string;
    'chainId': number;
    'transactionIntents': Array<TransactionIntentResponse>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "string",
            "format": ""
        },
        {
            "name": "deployed",
            "baseName": "deployed",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "object",
            "baseName": "object",
            "type": "string",
            "format": ""
        },
        {
            "name": "chainId",
            "baseName": "chain_id",
            "type": "number",
            "format": "double"
        },
        {
            "name": "transactionIntents",
            "baseName": "transaction_intents",
            "type": "Array<TransactionIntentResponse>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AccountResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

