/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://openfort.xyz/docs
 *
 * OpenAPI spec version: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AssetType } from '../models/AssetType';
import { HttpFile } from '../http/http';

export class AssetInventory {
    'assetType': AssetType;
    'address'?: string;
    'tokenId'?: number;
    /**
    * amount in Wei
    */
    'amount'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "assetType",
            "baseName": "asset_type",
            "type": "AssetType",
            "format": ""
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "string",
            "format": ""
        },
        {
            "name": "tokenId",
            "baseName": "token_id",
            "type": "number",
            "format": "double"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number",
            "format": "double"
        }    ];

    static getAttributeTypeMap() {
        return AssetInventory.attributeTypeMap;
    }

    public constructor() {
    }
}



