/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://openfort.xyz/docs
 *
 * OpenAPI spec version: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ContractResponseAbi } from '../models/ContractResponseAbi';
import { HttpFile } from '../http/http';

export class ContractResponse {
    'id': string;
    'createdAt': Date;
    'name': string | null;
    'chainId': number;
    'address': string;
    'abi': ContractResponseAbi;
    'publicVerification': boolean;
    'object': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "chainId",
            "baseName": "chain_id",
            "type": "number",
            "format": "double"
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "string",
            "format": ""
        },
        {
            "name": "abi",
            "baseName": "abi",
            "type": "ContractResponseAbi",
            "format": ""
        },
        {
            "name": "publicVerification",
            "baseName": "public_verification",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "object",
            "baseName": "object",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ContractResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

