/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://openfort.xyz/docs
 *
 * OpenAPI spec version: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class JsonFragment {
    'name'?: string;
    'type'?: string;
    'anonymous'?: boolean;
    'payable'?: boolean;
    'constant'?: boolean;
    'stateMutability'?: string;
    'inputs'?: any;
    'outputs'?: any;
    'gas'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "anonymous",
            "baseName": "anonymous",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "payable",
            "baseName": "payable",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "constant",
            "baseName": "constant",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "stateMutability",
            "baseName": "stateMutability",
            "type": "string",
            "format": ""
        },
        {
            "name": "inputs",
            "baseName": "inputs",
            "type": "any",
            "format": ""
        },
        {
            "name": "outputs",
            "baseName": "outputs",
            "type": "any",
            "format": ""
        },
        {
            "name": "gas",
            "baseName": "gas",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return JsonFragment.attributeTypeMap;
    }

    public constructor() {
    }
}

