/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://openfort.xyz/docs
 *
 * OpenAPI spec version: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class Log {
    'id': string;
    'timestamp': string;
    'event': string;
    'requestBody': any | null;
    'status': number;
    'responseTime': number;
    'responseData': any | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "string",
            "format": ""
        },
        {
            "name": "event",
            "baseName": "event",
            "type": "string",
            "format": ""
        },
        {
            "name": "requestBody",
            "baseName": "request_body",
            "type": "any",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "number",
            "format": "double"
        },
        {
            "name": "responseTime",
            "baseName": "response_time",
            "type": "number",
            "format": "double"
        },
        {
            "name": "responseData",
            "baseName": "response_data",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Log.attributeTypeMap;
    }

    public constructor() {
    }
}

