/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://openfort.xyz/docs
 *
 * OpenAPI spec version: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AllowFunctionResponse } from '../models/AllowFunctionResponse';
import { Strategy } from '../models/Strategy';
import { HttpFile } from '../http/http';

export class PolicyResponse {
    'id': string;
    'createdAt': Date;
    'name': string | null;
    'chainId': number;
    'strategy': Strategy;
    'transactionIntents': Array<any>;
    'allowFunctions': Array<AllowFunctionResponse>;
    'object': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "chainId",
            "baseName": "chain_id",
            "type": "number",
            "format": "double"
        },
        {
            "name": "strategy",
            "baseName": "strategy",
            "type": "Strategy",
            "format": ""
        },
        {
            "name": "transactionIntents",
            "baseName": "transaction_intents",
            "type": "Array<any>",
            "format": ""
        },
        {
            "name": "allowFunctions",
            "baseName": "allow_functions",
            "type": "Array<AllowFunctionResponse>",
            "format": ""
        },
        {
            "name": "object",
            "baseName": "object",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PolicyResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

