/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://openfort.xyz/docs
 *
 * OpenAPI spec version: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ResponseResponse {
    'createdAt': Date;
    'blockNumber': number | null;
    'transactionHash': string | null;
    'gasUsed': number;
    'status': number;
    'logs': Array<string>;
    'to': string;
    'error': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "blockNumber",
            "baseName": "block_number",
            "type": "number",
            "format": "double"
        },
        {
            "name": "transactionHash",
            "baseName": "transaction_hash",
            "type": "string",
            "format": ""
        },
        {
            "name": "gasUsed",
            "baseName": "gas_used",
            "type": "number",
            "format": "double"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "number",
            "format": "double"
        },
        {
            "name": "logs",
            "baseName": "logs",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "to",
            "baseName": "to",
            "type": "string",
            "format": ""
        },
        {
            "name": "error",
            "baseName": "error",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ResponseResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

